# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 45442d8e7934aa7ee3da2744f3e8ae7e4fd651a8e0209f6aa156d7acba1acc7eab1da606632614d1d3d68e8e2e0b7e2f766d7d761a36f4c6c3b9c32d9f951514

test:
  secret_key_base: 32e3ec22d19bad4ca30ac90b0645156b317f27e1d7a380cff0e7aad785ed28fbbcb13e7064c9642c11d4f2a289b3cd123389be13369af7757e6ed74e951f0ccc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
